# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Build
        run: go build -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Build binaries for multiple platforms
        run: |
          # Create release directory
          mkdir -p release

          # Build for Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o release/k8s-pod-log-analyzer-linux-amd64 .

          # Build for Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o release/k8s-pod-log-analyzer-linux-arm64 .

          # Build for macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o release/k8s-pod-log-analyzer-darwin-amd64 .

          # Build for macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o release/k8s-pod-log-analyzer-darwin-arm64 .

          # Build for Windows AMD64
          GOOS=windows GOARCH=amd64 go build -o release/k8s-pod-log-analyzer-windows-amd64.exe .

          # Build for Windows ARM64
          GOOS=windows GOARCH=arm64 go build -o release/k8s-pod-log-analyzer-windows-arm64.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
